# Practical_6: Numpy

---

### Exercise 1:
Create a NumPy array of integers from 1 to 10.

```python
# Exercise 1
```

---

In [18]:
import numpy as np
n=np.arange(1,11,1)
print(n)


[ 1  2  3  4  5  6  7  8  9 10]


numpy.ndarray

### Exercise 2:
Create a 3x3 NumPy array filled with zeros.

```python
# Exercise 2
```

---

In [3]:
import numpy as np
zero=np.zeros((3,3))
print(zero)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Exercise 3:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.

```python
# Exercise 3
```

---

In [6]:
import numpy as np
z=np.linspace(0,5,10)
print(z)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


### Exercise 4:
Create a 5x5 identity matrix using NumPy.

```python
# Exercise 4
```

---

In [9]:
import numpy as np
one=np.eye(5)
print(one)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.

```python
# Exercise 5
```

---

In [15]:
import numpy as np
rand=np.random.randint(2, size=(4,4))
print(rand)

[[0 0 0 0]
 [1 0 0 1]
 [0 1 1 1]
 [1 1 1 1]]


### Exercise 6:
Find the shape of a NumPy array.

```python
# Exercise 6
```

---

In [17]:
import numpy as np
rand=np.array([[1,2,3],[2,3,4],[6,7,8]])
print(rand)
rand.shape

[[1 2 3]
 [2 3 4]
 [6 7 8]]


(3, 3)

### Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.

```python
# Exercise 7
```

---

In [21]:
import numpy as np
n=np.arange(16)
print(n)
n.reshape(4,4)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

### Exercise 8:
Find the data type of the elements in a NumPy array.

```python
# Exercise 8
```

---

In [22]:
import numpy as np
n=np.arange(16)
type(n[4])

numpy.int64

### Exercise 9:
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.

```python
# Exercise 9
```

---

In [40]:
import numpy as np
n=np.arange(101)
x=[x1 for x1 in n if x1%2==0]
print(x)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]


### Exercise 10:
Generate a 6x6 matrix of random integers between 10 and 50.

```python
# Exercise 10
```

---

In [47]:
import numpy as np
n=np.random.randint(10,50, size=(6,6))
print(n)

[[26 20 48 30 32 22]
 [31 33 13 12 43 19]
 [10 32 47 46 41 29]
 [27 35 49 33 21 42]
 [16 24 21 18 32 48]
 [13 29 41 35 18 41]]


### Exercise 11:
Slice a 2D NumPy array to extract a submatrix.

```python
# Exercise 11
```

---

In [67]:
import numpy as np
n=np.random.random(30)
z=n[0:6]
print(z)

[0.80343162 0.03353524 0.40000136 0.60668971 0.396108   0.01323681]


### Exercise 12:
Calculate the sum of all elements in a NumPy array.

```python
# Exercise 12
```

---

In [75]:
import numpy as np
n=np.random.randint(50, size=(6,7))
s=np.sum(n)
print(s)

1209


### Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.

```python
# Exercise 13
```

---

In [77]:
import numpy as np
n=np.random.randint(50, size=(6,7))
mea=np.mean(n)
med=np.median(n)
stand=np.std(n)
print("The mean of", n, "is:", mea)
print("=====================================================\n")
print("The meadian of", n, "is:", med)
print("=====================================================\n")
print("Teh standart deviation of", n, "is:", stand)

The mean of [[ 9 31 37 37 18 32  8]
 [49 12 39 19  5 13 25]
 [17 37  6 25 44 16 37]
 [ 1  3 38 44 44 42 38]
 [26 23 37 10 25  3  0]
 [45 44  0  9  2  2  9]] is: 22.88095238095238

The meadian of [[ 9 31 37 37 18 32  8]
 [49 12 39 19  5 13 25]
 [17 37  6 25 44 16 37]
 [ 1  3 38 44 44 42 38]
 [26 23 37 10 25  3  0]
 [45 44  0  9  2  2  9]] is: 24.0

Teh standart deviation of [[ 9 31 37 37 18 32  8]
 [49 12 39 19  5 13 25]
 [17 37  6 25 44 16 37]
 [ 1  3 38 44 44 42 38]
 [26 23 37 10 25  3  0]
 [45 44  0  9  2  2  9]] is: 15.661907657559563


### Exercise 14:
Find the maximum and minimum values in a NumPy array.

```python
# Exercise 14
```

---

In [89]:
import numpy as np
n=np.random.randint(50, size=(6,7))
print(np.max(n, axis=0))#print the maximum element in each column
print(np.max(n, axis=1))#print the maximum element in each row
print(np.min(n, axis=0))#...
print(np.min(n, axis=1))#...

[44 29 46 43 38 47 43]
[43 43 41 46 47 41]
[ 1  2  5 14 14  3  1]
[1 6 2 3 1 9]


### Exercise 15:
Create a NumPy array of 20 random integers and find the index of the maximum value.

```python
# Exercise 15
```

---

In [100]:
import numpy as np
n=np.random.randint(20, size=(5,7))
print(n)
np.argmax(n)

[[12  7 13  3  7  5  9]
 [19  3  2  5  6 16  0]
 [ 0 13  9  1 11 16  3]
 [ 1  7  3  7  1 15 16]
 [14  3  2 14 10 13  7]]


7

### Exercise 16:
Create a NumPy array and reverse its elements.

```python
# Exercise 16
```

---

In [104]:
import numpy as np
n=np.random.randint(20, size=(7,7))
n1=np.linalg.inv(n)
#np.dot(n,n1)

array([[ 1.00000000e+00,  3.33066907e-16, -2.22044605e-16,
         1.11022302e-16,  1.11022302e-16, -5.55111512e-17,
         2.22044605e-16],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00,
        -2.22044605e-16, -2.22044605e-16,  5.55111512e-17,
         6.66133815e-16],
       [-1.33226763e-15,  7.77156117e-16,  1.00000000e+00,
         2.22044605e-16,  3.33066907e-16,  6.10622664e-16,
         4.44089210e-16],
       [ 4.44089210e-16,  2.22044605e-16, -2.22044605e-16,
         1.00000000e+00,  1.11022302e-16,  1.11022302e-16,
         0.00000000e+00],
       [-3.77475828e-15,  1.77635684e-15, -2.22044605e-16,
        -1.11022302e-16,  1.00000000e+00,  1.66533454e-16,
        -1.11022302e-16],
       [-6.66133815e-16,  1.88737914e-15,  0.00000000e+00,
         1.11022302e-16,  4.44089210e-16,  1.00000000e+00,
         1.11022302e-16],
       [ 1.83186799e-15,  3.05311332e-16, -2.77555756e-17,
         3.60822483e-16, -9.71445147e-17,  0.00000000e+00,
         1.0000000

### Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.

```python
# Exercise 17
```

---

In [106]:
import numpy as np
a=np.random.randint(20, size=(3,3))
b=np.random.randint(10, size=(3,3))
np.dot(a,b)

array([[ 49, 114,  13],
       [178, 137,  83],
       [ 99, 133,  50]])

### Exercise 18:
Create a diagonal matrix from a given 1D array.

```python
# Exercise 18
```

---

In [112]:
import numpy as np
a=np.random.randint(20, size=(10,))
x=np.diag(a)
print(a,"\n",x)

[16 14 16 19 14  4 17  9 18 19] 
 [[16  0  0  0  0  0  0  0  0  0]
 [ 0 14  0  0  0  0  0  0  0  0]
 [ 0  0 16  0  0  0  0  0  0  0]
 [ 0  0  0 19  0  0  0  0  0  0]
 [ 0  0  0  0 14  0  0  0  0  0]
 [ 0  0  0  0  0  4  0  0  0  0]
 [ 0  0  0  0  0  0 17  0  0  0]
 [ 0  0  0  0  0  0  0  9  0  0]
 [ 0  0  0  0  0  0  0  0 18  0]
 [ 0  0  0  0  0  0  0  0  0 19]]


### Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.

```python
# Exercise 19
```

---

In [115]:
import numpy as np
a=np.random.randint(20, size=(2,2))
b=np.random.randint(20, size=(2,2))
print(a,"\n", b)
print(np.dot(a,b))

[[ 2 16]
 [ 8 18]] 
 [[8 5]
 [9 3]]
[[160  58]
 [226  94]]


### Exercise 20:
Flatten a 2D NumPy array into a 1D array.

```python
# Exercise 20
```

---

In [124]:
import numpy as np
a=np.random.randint(20, size=(2,2))
x=np.reshape(a, newshape=(4,))
print(a,"\n", x)

[[ 4 19]
 [14 18]] 
 [ 4 19 14 18]


### Exercise 21:
Stack two NumPy arrays vertically.

```python
# Exercise 21
```

---

In [149]:
import numpy as np
a=np.random.randint(20, size=(2,2))
b=np.random.randint(20, size=(2,2))
c=np.vstack((a,b))
print(a,"\n",b)
print("=============================================\n")
print(c)

[[ 7 17]
 [ 4 16]] 
 [[ 1  1]
 [16  6]]

[[ 7 17]
 [ 4 16]
 [ 1  1]
 [16  6]]


### Exercise 22:
Stack two NumPy arrays horizontally.

```python
# Exercise 22
```

---

In [148]:
import numpy as np
a=np.random.randint(20, size=(2,2))
b=np.random.randint(20, size=(2,2))
c=np.hstack((a,b))
print(a,"\n",b)
print("=============================================\n")
print(c)

[[ 5 19]
 [ 1 11]] 
 [[17 17]
 [18  2]]

[[ 5 19 17 17]
 [ 1 11 18  2]]


### Exercise 23:
Split a NumPy array into multiple sub-arrays.

```python
# Exercise 23
```

---

In [146]:
import numpy as np
a=np.random.randint(20, size=(5,5))
print(a)
np.split(a, (2,3))

[[15  0 19 18  0]
 [10  1  6 18 19]
 [14 12  4  8 17]
 [ 1 12  0 10 17]
 [ 9 14 14  2 17]]


[array([[15,  0, 19, 18,  0],
        [10,  1,  6, 18, 19]]),
 array([[14, 12,  4,  8, 17]]),
 array([[ 1, 12,  0, 10, 17],
        [ 9, 14, 14,  2, 17]])]

### Exercise 24:
Generate a random NumPy array and round each element to two decimal places.

```python
# Exercise 24
```

---

In [162]:
import numpy as np
a=np.random.random(20)
print(a)
np.round_(a,decimals=2)

[0.95112138 0.19470656 0.47649233 0.34117173 0.57268317 0.83524512
 0.71331899 0.52478598 0.85421648 0.54869767 0.50386207 0.14525114
 0.7324633  0.11963518 0.55063467 0.62942909 0.19425012 0.86315045
 0.64275341 0.16345895]


array([0.95, 0.19, 0.48, 0.34, 0.57, 0.84, 0.71, 0.52, 0.85, 0.55, 0.5 ,
       0.15, 0.73, 0.12, 0.55, 0.63, 0.19, 0.86, 0.64, 0.16])

In [153]:
help(np.round)

Help on function round_ in module numpy:

round_(a, decimals=0, out=None)
    Round an array to the given number of decimals.
    
    See Also
    --------
    around : equivalent function; see for details.



### Exercise 25:
Find the unique elements of a NumPy array.

```python
# Exercise 25
```

---

In [165]:
import numpy as np
a=np.random.random(20)
print(a)
np.unique(a)

[0.13362384 0.24558845 0.29269049 0.58727788 0.36918177 0.46480738
 0.4887352  0.01098047 0.75382203 0.20454249 0.64819762 0.99559852
 0.98057856 0.5288756  0.77975582 0.95839904 0.95766583 0.2409898
 0.28260345 0.05437845]


array([0.01098047, 0.05437845, 0.13362384, 0.20454249, 0.2409898 ,
       0.24558845, 0.28260345, 0.29269049, 0.36918177, 0.46480738,
       0.4887352 , 0.5288756 , 0.58727788, 0.64819762, 0.75382203,
       0.77975582, 0.95766583, 0.95839904, 0.98057856, 0.99559852])

### Exercise 26:
Replace all elements in a NumPy array that are less than a specific value with that value.

```python
# Exercise 26
```

---

In [173]:
import numpy as np
a=np.random.random(20)
print(a)
a[a<a[2]]=a[2]
print("=======================================\n")
print(a)

[0.45635123 0.46479971 0.14566336 0.31023912 0.09964699 0.14888329
 0.02671656 0.41390413 0.85042316 0.91884855 0.95515744 0.19621616
 0.6181044  0.43520513 0.19005743 0.58603153 0.40965248 0.05829379
 0.68431438 0.18418824]

[0.45635123 0.46479971 0.14566336 0.31023912 0.14566336 0.14888329
 0.14566336 0.41390413 0.85042316 0.91884855 0.95515744 0.19621616
 0.6181044  0.43520513 0.19005743 0.58603153 0.40965248 0.14566336
 0.68431438 0.18418824]


### Exercise 27:
Find the cumulative sum of the elements in a NumPy array.

```python
# Exercise 27
```

---

In [177]:
import numpy as np
a=np.random.random(20)
x=np.cumsum(a)
print(a)
print("=============================\n")
print(x)

[0.60565886 0.94516066 0.85097484 0.21896264 0.02549738 0.49127016
 0.66940464 0.0655054  0.2048288  0.21186405 0.9536526  0.19910023
 0.11571306 0.64744651 0.08438865 0.23243636 0.42584453 0.34694334
 0.0402246  0.68149064]

[0.60565886 1.55081952 2.40179436 2.620757   2.64625438 3.13752454
 3.80692918 3.87243458 4.07726338 4.28912743 5.24278003 5.44188026
 5.55759332 6.20503983 6.28942848 6.52186484 6.94770938 7.29465271
 7.33487731 8.01636795]


In [178]:
import numpy as np
a=np.random.random(20)
x=np.cumsum(a, axis=0)
print(a)
print("=============================\n")
print(x)

[0.45818154 0.16957169 0.70391447 0.69763447 0.52543451 0.75481925
 0.88335333 0.26549486 0.09089573 0.6231358  0.45778489 0.01229237
 0.22008567 0.49646869 0.34277333 0.10469643 0.9795841  0.82435822
 0.29887565 0.06851836]

[0.45818154 0.62775322 1.33166769 2.02930216 2.55473667 3.30955592
 4.19290925 4.45840411 4.54929984 5.17243564 5.63022053 5.6425129
 5.86259858 6.35906727 6.7018406  6.80653702 7.78612113 8.61047935
 8.909355   8.97787336]


### Exercise 28:
Create a NumPy array and find the number of non-zero elements in it.

```python
# Exercise 28
```

---

In [192]:
import numpy as np
a=np.random.random(20)
print(a)
x=np.count_nonzero(a)
print(x)

[0.90470883 0.13193602 0.42031066 0.35296435 0.69798626 0.76238266
 0.61975568 0.00548411 0.47727268 0.68104507 0.42567284 0.15517087
 0.59949415 0.6551699  0.04847856 0.56947612 0.53151828 0.29284646
 0.48624676 0.13515207]
20


### Exercise 29:
Create a NumPy array of random integers and sort it in ascending order.

```python
# Exercise 29
```

---

In [184]:
import numpy as np
a=np.random.randint(20, size=(4,4))
print(a)
np.sort(a, axis=None)

[[14 18  6 11]
 [ 2  3 13 13]
 [19 14  4 16]
 [ 4  8  2 13]]


array([ 2,  2,  3,  4,  4,  6,  8, 11, 13, 13, 13, 14, 14, 16, 18, 19])

In [181]:
help(np.sort)

Help on function sort in module numpy:

sort(a, axis=-1, kind=None, order=None)
    Return a sorted copy of an array.
    
    Parameters
    ----------
    a : array_like
        Array to be sorted.
    axis : int or None, optional
        Axis along which to sort. If None, the array is flattened before
        sorting. The default is -1, which sorts along the last axis.
    kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
        Sorting algorithm. The default is 'quicksort'. Note that both 'stable'
        and 'mergesort' use timsort or radix sort under the covers and, in general,
        the actual implementation will vary with data type. The 'mergesort' option
        is retained for backwards compatibility.
    
        .. versionchanged:: 1.15.0.
           The 'stable' option was added.
    
    order : str or list of str, optional
        When `a` is an array with fields defined, this argument specifies
        which fields to compare first, second, etc.  A si

### Exercise 30:
Find the row-wise and column-wise sum of a 3x3 matrix.

```python
# Exercise 30
```

---

In [197]:
import numpy as np
a=np.random.randint(20, size=(3,3))
print(a)
row=np.sum(a, axis=1)
col=np.sum(a, axis=0)
print("==============================================\n")
print(row,"\n",col)

[[ 9 19 12]
 [ 3 14 12]
 [ 9 10  5]]

[40 29 24] 
 [21 43 29]


### Exercise 31:
Generate a 2D NumPy array with random values and normalize it (scale the values between 0 and 1).

```python
# Exercise 31
```

---

In [206]:
import numpy as np
a=np.random.randint(20, size=(2,2))
print(a)
a_norm=(a-np.min(a))/(np.max(a)-np.min(a))
print(a_norm)

[[ 5 18]
 [ 2 15]]
[[0.1875 1.    ]
 [0.     0.8125]]


### Exercise 32:
Create two NumPy arrays and find the dot product.

```python
# Exercise 32
```

---

In [209]:
import numpy as np
a=np.random.randint(20, size=(2,2))
b=np.random.randint(20, size=(2,2))
print(np.dot(a,b))

[[ 81  48]
 [128 144]]


### Exercise 33:
Find the trace of a square NumPy matrix.

```python
# Exercise 33
```

---

In [210]:
import numpy as np
a=np.random.randint(20, size=(2,2))
v=np.trace(a)
print(v)

27


### Exercise 34:
Create a 2D array and swap two rows.

```python
# Exercise 34
```

---

In [219]:
import numpy as np
a=np.random.randint(20, size=(2,2))
print(a)
np.swapaxes(a,axis1=1, axis2=0)

[[ 0  9]
 [15  6]]


array([[ 0, 15],
       [ 9,  6]])

### Exercise 35:
Create a 1D NumPy array and convert it into a column vector.

```python
# Exercise 35
```

---

In [226]:
import numpy as np
a=np.arange(10)
b=a.reshape(10,1)
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


### Exercise 36:
Find the determinant of a 3x3 matrix.

```python
# Exercise 36
```

---

In [229]:
import numpy as np
a=np.random.randint(20, size=(3,3))
print(a)
x=np.linalg.det(a)
print(x)

[[12 13 18]
 [10 14  6]
 [ 7  9 16]]
362.00000000000017


### Exercise 37:
Find the eigenvalues and eigenvectors of a 2x2 matrix.

```python
# Exercise 37
```

---

In [245]:
import numpy as np
a=np.random.randint(20, size=(2,2))
x=np.linalg.eigvals(a)
print(a)
print(x)

[[ 0  4]
 [17 16]]
[-3.48912529 19.48912529]


### Exercise 38:
Solve a system of linear equations using NumPy.

```python
# Exercise 38
```

---

In [251]:
import numpy as np
a=np.random.randint(20, size=(3,3))
b=np.arange(1,4,1)
x=np.linalg.inv(a).dot(b)
print(x)

[-0.01419966  0.18416523 -0.00387263]


### Exercise 39:
Add Gaussian noise to a NumPy array.

```python
# Exercise 39
```

---

In [254]:
import numpy as np
a=np.random.randint(20, size=(4,4))
d=np.extract
help(np.extract)

Help on function extract in module numpy:

extract(condition, arr)
    Return the elements of an array that satisfy some condition.
    
    This is equivalent to ``np.compress(ravel(condition), ravel(arr))``.  If
    `condition` is boolean ``np.extract`` is equivalent to ``arr[condition]``.
    
    Note that `place` does the exact opposite of `extract`.
    
    Parameters
    ----------
    condition : array_like
        An array whose nonzero or True entries indicate the elements of `arr`
        to extract.
    arr : array_like
        Input array of the same size as `condition`.
    
    Returns
    -------
    extract : ndarray
        Rank 1 array of values from `arr` where `condition` is True.
    
    See Also
    --------
    take, put, copyto, compress, place
    
    Examples
    --------
    >>> arr = np.arange(12).reshape((3, 4))
    >>> arr
    array([[ 0,  1,  2,  3],
           [ 4,  5,  6,  7],
           [ 8,  9, 10, 11]])
    >>> condition = np.mod(arr, 3)==0
    >

### Exercise 41:
Generate a NumPy array of 100 random values and clip the values to a range between 10 and 50.

```python
# Exercise 41
```

---

In [244]:
import numpy as np
a=np.random.random(100)
print(a)
np.clip(a, 10, 50, out=None)

[0.04429553 0.59486176 0.06274479 0.94617157 0.24833879 0.7316151
 0.43406716 0.50530569 0.87566005 0.40453619 0.16039545 0.52069685
 0.11701256 0.74158071 0.54491624 0.54454639 0.89401612 0.25114468
 0.80285484 0.08243555 0.40381276 0.37355116 0.10246557 0.48229717
 0.51767738 0.6014889  0.42739061 0.78106615 0.88597365 0.09597482
 0.17012956 0.78900268 0.78618717 0.76922657 0.90854068 0.93184381
 0.47255096 0.92851206 0.34554312 0.58174037 0.55922334 0.71543996
 0.13507433 0.73546137 0.83088678 0.24754762 0.72919408 0.12608155
 0.27902842 0.2639147  0.03454087 0.07537106 0.76100534 0.0058047
 0.69003766 0.88161629 0.61032643 0.53719794 0.13790481 0.85487029
 0.19503109 0.75997821 0.99220444 0.00902117 0.11600188 0.40810695
 0.9663106  0.3368816  0.10744217 0.78703161 0.47757929 0.20591039
 0.38212615 0.15883472 0.09103531 0.5960876  0.47893048 0.09218887
 0.80525748 0.49582885 0.37441498 0.6260525  0.07887209 0.88136938
 0.14174925 0.05052373 0.53565208 0.49871688 0.81198785 0.694835

array([10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
       10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
       10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
       10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
       10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
       10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
       10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
       10., 10., 10., 10., 10., 10., 10., 10., 10.])

### Exercise 42:
Create a 2D NumPy array and replace all negative values with zero.

```python
# Exercise 42
```

---

In [237]:
import numpy as np
a=np.arange(-2,2,1).reshape(2,2)
a[a<0]=0
print(a)

[[0 0]
 [0 1]]


### Exercise 43:
Find the inner and outer products of two NumPy arrays.

```python
# Exercise 43
```

---

In [247]:
import numpy as np
a=np.random.randint(20, size=(3,3))
b=np.random.randint(20, size=(3,3))
print(a.dot(b))#inner product
print(np.outer(a,b))#outer product

[[622 371 329]
 [401 286 222]
 [715 398 390]]
[[198  99 121 187 165  99 209  44  88]
 [288 144 176 272 240 144 304  64 128]
 [144  72  88 136 120  72 152  32  64]
 [144  72  88 136 120  72 152  32  64]
 [252 126 154 238 210 126 266  56 112]
 [ 18   9  11  17  15   9  19   4   8]
 [342 171 209 323 285 171 361  76 152]
 [234 117 143 221 195 117 247  52 104]
 [144  72  88 136 120  72 152  32  64]]


### Exercise 44:
Calculate the pairwise distances between points in a NumPy array.

```python
# Exercise 44
```

---

### Exercise 45:
Create a structured NumPy array with fields for `name`, `age`, and `height`.

```python
# Exercise 45
```

---

### Exercise 46:
Create a 5x5 matrix of random integers and count the occurrences of each unique value.

```python
# Exercise 46
```

---

### Exercise 47:
Generate a random 3x3 NumPy array and subtract the mean of each row from the corresponding row.

```python
# Exercise 47
```

---

### Exercise 48:
Create a NumPy array of random integers and check if any of the values are greater than 50.

```python
# Exercise 48
```

---

### Exercise 49:
Calculate the moving average of a 1D NumPy array.

```python
# Exercise 49
```

---

### Exercise 50:
Find the Pearson correlation coefficient between two NumPy arrays.

```python
# Exercise 50
```

---

### Exercise 51:
Convert a NumPy array of radians to degrees.

```python
# Exercise 51
```

---

### Exercise 52:
Create a random NumPy array and compute its variance and standard deviation.

```python
# Exercise 52
```

---

### Exercise 53:
Create a 2D NumPy array and find the indices of the maximum values along each axis.

```python
# Exercise 53
```

---

### Exercise 54:
Compute the inverse of a 2x2 NumPy matrix.

```python
# Exercise 54
```

---

### Exercise 55:
Create a NumPy array of 10 random values and standardize it (mean 0, variance 1).

```python
# Exercise 55
```

---

### Exercise 56:
Perform element-wise addition and subtraction on two NumPy arrays.

```python
# Exercise 56
```

---

### Exercise 57:
Create a NumPy array of random values and find the maximum element's index.

```python
# Exercise 57
```

---

### Exercise 58:
Create a 3x3 NumPy array and rotate it by 90 degrees.

```python
# Exercise 58
```

---

### Exercise 59:
Compute the Frobenius norm of a matrix.

```python
# Exercise 59
```

---

### Exercise 60:
Create a 3D NumPy array and slice out a subarray.

```python
# Exercise 60
```

---